# Generated by Django 5.2.4 on 2025-07-07 06:22

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], db_index=True, default='LOW', max_length=20)),
                ('risk_score', models.IntegerField(default=0, help_text='Risk score between 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_assessment_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('risk_assessment_notes', models.TextField(blank=True)),
                ('previous_risk_levels', models.JSONField(default=list, help_text='History of risk level changes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata')),
                ('hash', models.CharField(blank=True, help_text='SHA-256 hash of critical fields', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold'), ('EXPIRED', 'Expired'), ('BLOCKED', 'Blocked')], db_index=True, default='PENDING', max_length=50)),
                ('status_changed_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status_reason', models.TextField(blank=True)),
                ('status_history', models.JSONField(default=list, help_text='History of status changes')),
                ('customer_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('customer_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('CORPORATE', 'Corporate'), ('SOLE_PROPRIETOR', 'Sole Proprietor'), ('PARTNERSHIP', 'Partnership'), ('LLC', 'Limited Liability Company'), ('TRUST', 'Trust'), ('GOVERNMENT', 'Government Entity'), ('NGO', 'Non-Governmental Organization')], db_index=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('nationality', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('identification_type', models.CharField(max_length=50)),
                ('identification_number', models.CharField(max_length=100)),
                ('is_pep', models.BooleanField(db_index=True, default=False)),
                ('is_sanctioned', models.BooleanField(db_index=True, default=False)),
                ('kyc_status', models.CharField(default='PENDING', max_length=50)),
                ('kyc_expiry', models.DateField(blank=True, null=True)),
                ('kyc_documents', models.JSONField(default=list)),
                ('risk_factors', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata')),
                ('hash', models.CharField(blank=True, help_text='SHA-256 hash of critical fields', max_length=64)),
                ('address_type', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('BUSINESS', 'Business'), ('MAILING', 'Mailing'), ('OTHER', 'Other')], max_length=50)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('verification_method', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Customer Address',
                'verbose_name_plural': 'Customer Addresses',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata')),
                ('hash', models.CharField(blank=True, help_text='SHA-256 hash of critical fields', max_length=64)),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('ID_CARD', 'ID Card'), ('DRIVING_LICENSE', 'Driving License'), ('TRADE_LICENSE', 'Trade License'), ('OTHER', 'Other')], max_length=50)),
                ('document_number', models.CharField(max_length=100)),
                ('issuing_country', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('file_path', models.FileField(upload_to='customer_documents/%Y/%m/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('verification_method', models.CharField(blank=True, max_length=50)),
                ('verification_result', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Customer Document',
                'verbose_name_plural': 'Customer Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
