# Generated by Django 5.2.4 on 2025-07-07 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customer_management.customer'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customer_management.customer'),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type', 'kyc_status'], name='customer_ma_custome_859aa3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_pep', 'is_sanctioned'], name='customer_ma_is_pep_32890a_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['identification_type', 'identification_number'], name='customer_ma_identif_4091fc_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraddress',
            index=models.Index(fields=['address_type', 'country'], name='customer_ma_address_f9104b_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraddress',
            index=models.Index(fields=['is_primary', 'is_verified'], name='customer_ma_is_prim_98ee94_idx'),
        ),
        migrations.AddIndex(
            model_name='customerdocument',
            index=models.Index(fields=['document_type', 'issuing_country'], name='customer_ma_documen_3bd099_idx'),
        ),
        migrations.AddIndex(
            model_name='customerdocument',
            index=models.Index(fields=['is_verified', 'expiry_date'], name='customer_ma_is_veri_afbd69_idx'),
        ),
    ]
