# Generated by Django 5.2.4 on 2025-07-09 11:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0001_initial'),
        ('customer_management', '0003_customer_last_segment_review_and_more'),
        ('transaction_monitoring', '0003_monitoringrule_transactionalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRegulatoryReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata')),
                ('hash', models.CharField(blank=True, help_text='SHA-256 hash of critical fields', max_length=64)),
                ('report_type', models.CharField(choices=[('FINTRAC', 'FINTRAC Report'), ('AUSTRAC', 'AUSTRAC Report'), ('FINCEN', 'FinCEN Report'), ('OTHER', 'Other Report')], max_length=50)),
                ('report_data', models.JSONField(help_text='Report data in required format')),
                ('submission_status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready for Submission'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=50)),
                ('reference_number', models.CharField(blank=True, help_text='Reference number from regulatory system', max_length=100)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgment', models.JSONField(blank=True, help_text='Acknowledgment from regulatory system', null=True)),
            ],
            options={
                'verbose_name': 'case regulatory report',
                'verbose_name_plural': 'case regulatory reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='regulatoryreport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='regulatoryreport',
            name='prepared_by',
        ),
        migrations.RemoveField(
            model_name='regulatoryreport',
            name='sar_case',
        ),
        migrations.RemoveField(
            model_name='regulatoryreport',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='regulatoryreport',
            name='updated_by',
        ),
        migrations.RemoveIndex(
            model_name='casedecision',
            name='case_manage_decisio_1b3d98_idx',
        ),
        migrations.RemoveIndex(
            model_name='goamlsubmission',
            name='case_manage_report__356bdf_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatoryfiling',
            name='case_manage_case_id_cbf9e1_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatoryfiling',
            name='case_manage_status_8f162e_idx',
        ),
        migrations.RemoveIndex(
            model_name='sarcase',
            name='case_manage_filing__976561_idx',
        ),
        migrations.RenameIndex(
            model_name='case',
            new_name='case_manage_assigne_5fa77b_idx',
            old_name='case_manage_assigne_179ba6_idx',
        ),
        migrations.AlterField(
            model_name='case',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='escalated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caseactivity',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casedecision',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_case_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casedecision',
            name='decision_maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_case_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='regulatoryfiling',
            name='prepared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_filings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='regulatoryfiling',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_filings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='regulatoryfiling',
            name='submission_response',
            field=models.JSONField(blank=True, help_text='Response from regulatory system', null=True),
        ),
        migrations.AlterField(
            model_name='regulatoryfiling',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_filings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='casedecision',
            index=models.Index(fields=['decision_maker'], name='case_manage_decisio_c19cf7_idx'),
        ),
        migrations.AddIndex(
            model_name='goamlsubmission',
            index=models.Index(fields=['submission_status'], name='case_manage_submiss_ac9e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryfiling',
            index=models.Index(fields=['filing_type', 'status'], name='case_manage_filing__5383dd_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryfiling',
            index=models.Index(fields=['regulatory_body'], name='case_manage_regulat_c9dbc2_idx'),
        ),
        migrations.AddIndex(
            model_name='sarcase',
            index=models.Index(fields=['assigned_to'], name='case_manage_assigne_75145a_idx'),
        ),
        migrations.AddField(
            model_name='caseregulatoryreport',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caseregulatoryreport',
            name='prepared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_prepared_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caseregulatoryreport',
            name='sar_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_reports', to='case_management.sarcase'),
        ),
        migrations.AddField(
            model_name='caseregulatoryreport',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_submitted_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caseregulatoryreport',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RegulatoryReport',
        ),
        migrations.AddIndex(
            model_name='caseregulatoryreport',
            index=models.Index(fields=['report_type', 'submission_status'], name='case_manage_report__e651f6_idx'),
        ),
        migrations.AddIndex(
            model_name='caseregulatoryreport',
            index=models.Index(fields=['reference_number'], name='case_manage_referen_052556_idx'),
        ),
    ]
