# Generated by Django 5.2.4 on 2025-07-09 11:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0003_customer_last_segment_review_and_more'),
        ('risk_scoring', '0001_initial'),
        ('transaction_monitoring', '0003_monitoringrule_transactionalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eddapproval',
            name='risk_scorin_decisio_ff26b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='eddapproval',
            name='risk_scorin_approva_e808f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='eddrequest',
            name='risk_scorin_status_1a3a0f_idx',
        ),
        migrations.RemoveIndex(
            model_name='eddrequest',
            name='risk_scorin_request_6079b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='eddreview',
            name='risk_scorin_recomme_b4e94a_idx',
        ),
        migrations.RemoveIndex(
            model_name='eddreview',
            name='risk_scorin_review__bef5cb_idx',
        ),
        migrations.RemoveIndex(
            model_name='riskassessment',
            name='risk_scorin_custome_8a69e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='riskmodelversion',
            name='risk_scorin_model_n_19cf54_idx',
        ),
        migrations.AddField(
            model_name='eddrequest',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eddrequest',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eddrequest',
            name='escalation_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eddreview',
            name='findings',
            field=models.JSONField(default=dict, help_text='Structured findings captured during review'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kyc_requirements',
            field=models.JSONField(default=dict, help_text='KYC requirements for this product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='regulatory_requirements',
            field=models.JSONField(default=dict, help_text='Regulatory requirements and restrictions'),
        ),
        migrations.AlterField(
            model_name='product',
            name='risk_factors',
            field=models.JSONField(default=dict, help_text='Specific risk factors for this product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='transaction_limits',
            field=models.JSONField(default=dict, help_text='Transaction limits and thresholds'),
        ),
        migrations.AlterField(
            model_name='region',
            name='risk_factors',
            field=models.JSONField(default=dict, help_text='Specific risk factors for this region'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='factors_considered',
            field=models.JSONField(default=dict, help_text='Risk factors considered in assessment'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='mitigating_factors',
            field=models.JSONField(default=dict, help_text='Risk mitigating factors'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='risk_scores',
            field=models.JSONField(default=dict, help_text='Category-wise risk scores'),
        ),
        migrations.AlterField(
            model_name='riskcategory',
            name='custom_formula',
            field=models.JSONField(default=dict, help_text='Custom scoring formula configuration'),
        ),
        migrations.AlterField(
            model_name='riskcategory',
            name='risk_factors',
            field=models.JSONField(default=dict, help_text='Risk factors and their weights'),
        ),
        migrations.AlterField(
            model_name='riskcategory',
            name='thresholds',
            field=models.JSONField(default=dict, help_text='Risk level thresholds'),
        ),
        migrations.AlterField(
            model_name='riskfactor',
            name='weight',
            field=models.FloatField(help_text='Weight factor (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='riskmatrix',
            name='mitigation_rules',
            field=models.JSONField(default=dict, help_text='Risk mitigation rules'),
        ),
        migrations.AlterField(
            model_name='riskmatrix',
            name='risk_levels',
            field=models.JSONField(default=dict, help_text='Risk level definitions'),
        ),
        migrations.AlterField(
            model_name='riskmatrix',
            name='scoring_criteria',
            field=models.JSONField(default=dict, help_text='Scoring criteria for each cell'),
        ),
        migrations.AlterField(
            model_name='riskmatrix',
            name='thresholds',
            field=models.JSONField(default=dict, help_text='Threshold values for risk levels'),
        ),
        migrations.AlterField(
            model_name='riskmodelversion',
            name='model_parameters',
            field=models.JSONField(default=dict, help_text='Model parameters and configuration'),
        ),
        migrations.AlterField(
            model_name='riskmodelversion',
            name='performance_metrics',
            field=models.JSONField(default=dict, help_text='Model performance metrics'),
        ),
        migrations.AlterField(
            model_name='riskmodelversion',
            name='training_data',
            field=models.JSONField(default=dict, help_text='Training data summary'),
        ),
        migrations.AlterField(
            model_name='riskmodelversion',
            name='validation_results',
            field=models.JSONField(default=dict, help_text='Model validation results'),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='base_score',
            field=models.FloatField(help_text='Base risk score calculated from static factors', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='behavioral_score',
            field=models.FloatField(help_text='Score based on behavioral analysis', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='confidence_level',
            field=models.FloatField(help_text='Confidence level of the risk score', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='customer_management.customer'),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='historical_scores',
            field=models.JSONField(default=list, help_text='Historical risk score data'),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='ml_score',
            field=models.FloatField(help_text='Machine learning based risk score', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='risk_factors',
            field=models.JSONField(default=dict, help_text='Detailed breakdown of risk factors'),
        ),
        migrations.AddIndex(
            model_name='eddapproval',
            index=models.Index(fields=['request', 'decision'], name='risk_scorin_request_c69f97_idx'),
        ),
        migrations.AddIndex(
            model_name='eddapproval',
            index=models.Index(fields=['approver'], name='risk_scorin_approve_f9a84f_idx'),
        ),
        migrations.AddIndex(
            model_name='eddrequest',
            index=models.Index(fields=['customer', 'status'], name='risk_scorin_custome_ce6fca_idx'),
        ),
        migrations.AddIndex(
            model_name='eddrequest',
            index=models.Index(fields=['risk_level_at_request'], name='risk_scorin_risk_le_f9be31_idx'),
        ),
        migrations.AddIndex(
            model_name='eddrequest',
            index=models.Index(fields=['due_date'], name='risk_scorin_due_dat_41a7cf_idx'),
        ),
        migrations.AddIndex(
            model_name='eddreview',
            index=models.Index(fields=['request', 'recommendation'], name='risk_scorin_request_cad797_idx'),
        ),
        migrations.AddIndex(
            model_name='eddreview',
            index=models.Index(fields=['reviewer'], name='risk_scorin_reviewe_ef1523_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['sanctions_status'], name='risk_scorin_sanctio_1943a1_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['assessment_type', 'customer'], name='risk_scorin_assessm_fc864d_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['next_review_date'], name='risk_scorin_next_re_6523e7_idx'),
        ),
        migrations.AddIndex(
            model_name='riskfactor',
            index=models.Index(fields=['category', 'is_active'], name='risk_scorin_categor_77923a_idx'),
        ),
        migrations.AddIndex(
            model_name='riskmodelversion',
            index=models.Index(fields=['model_name', 'is_active'], name='risk_scorin_model_n_e47c98_idx'),
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['next_assessment'], name='risk_scorin_next_as_612e7d_idx'),
        ),
    ]
