# Generated by Django 5.2.4 on 2025-07-07 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryRiskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], db_index=True, default='LOW', max_length=20)),
                ('risk_score', models.IntegerField(default=0, help_text='Risk score between 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_assessment_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('risk_assessment_notes', models.TextField(blank=True)),
                ('risk_factors', models.JSONField(default=dict, help_text='Factors contributing to risk score')),
                ('previous_risk_levels', models.JSONField(default=list, help_text='History of risk level changes')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sanctions_data', models.JSONField(default=dict, help_text='Sanctions and restrictions data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country Risk Category',
                'verbose_name_plural': 'Country Risk Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code', 'is_active'], name='core_countr_code_5dc65b_idx'), models.Index(fields=['risk_level', 'is_active'], name='core_countr_risk_le_3e92be_idx')],
            },
        ),
    ]
